// <auto-generated />
using System;
using Angular_Ex1_Backend.Database.CodeFirst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Angular_Ex1_Backend.Database.DbMigration
{
    [DbContext(typeof(AngularTest1DbContext))]
    [Migration("20210122092605_Test-Angular-1")]
    partial class TestAngular1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Angular_Ex1_Backend.Database.CodeFirst.ReservationCoverage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("InstanceType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("MonthYear")
                        .HasColumnType("datetime");

                    b.Property<uint>("ReservedHours")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TotalHours")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("ReservationCoverages");
                });

            modelBuilder.Entity("Angular_Ex1_Backend.Database.CodeFirst.ServicesBill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("Bill")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("ServicesName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ServicesBill");
                });
#pragma warning restore 612, 618
        }
    }
}
